AWSTemplateFormatVersion: "2010-09-09"
Parameters:
 DomainName:
   Type: String
 #  AllowedPattern: ^([a-z])([a-z0-9\.\-])*$
   Default: ""
 TTL:
   Type: Number
   Default: 600
 #MxRecords:
  # Type: CommaDelimitedList
  # Description: >-
  #   A comma-separated list of entries for MX servers. Each entry
  #   should have a priority and domain name, separated by a space.
  # Default: 10 spool.mail.gandi.net,50 fb.mail.gandi.net
 #ApexRecords:
 #  Type: CommaDelimitedList
 #  Description: >-
 #    The default here is for GitHub Pages, cf
 #    https://help.github.com/articles/setting-up-an-apex-domain/
 #  Default: 192.30.252.153,192.30.252.154
 WwwRecord:
   Type: String
   Description: >-
     Set up www.example.net as CNAME for this address
   Default: stig.github.io
Resources:
 Zone:
   Type: 'AWS::Route53::HostedZone'
   Properties:
     Name: !Ref DomainName
     HostedZoneConfig:
       Comment: !Sub "My hosted zone for ${DomainName}"
 #MxRecordSet:
 #  Type: 'AWS::Route53::RecordSet'
 #  Properties:
 #    Name: !Ref DomainName
 #    HostedZoneId: !Ref Zone
 #    Type: MX
 #    TTL: !Ref TTL
 #    ResourceRecords: !Ref MxRecords
 #ApexRecordSet:
 #  Type: 'AWS::Route53::RecordSet'
 #  Properties:
 #    Name: !Ref DomainName
 #    HostedZoneId: !Ref Zone
 #    Type: A
 #    TTL: !Ref TTL
 #    ResourceRecords: !Ref ApexRecords
 WwwRecordSet:
   Type: 'AWS::Route53::RecordSet'
   Properties:
     Name: !Sub "www.${DomainName}."
     HostedZoneId: !Ref Zone
     Type: CNAME
     TTL: !Ref TTL
     ResourceRecords:
       - !Ref WwwRecord
 DomainRecordSet:
   Type: 'AWS::Route53::RecordSet'
   Properties:
     Name: !Sub "${DomainName}."
     HostedZoneId: !Ref Zone
     Type: A
     AliasTarget: !Ref WwwRecord
