AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Prefix:
    Type: String
    Default: "web2cloud-test"
  Landscape:
    Type: String
    Default: "test"
  RouterImage:
    Type: String
    Default: "amazon/amazon-ecs-sample"
  RouterTag:
    Type: String
    Default: "latest"
  CloudwatchLogsGroup:
    Type: String
    Description: Reference to logs group for ECS cluster apps
  ECSCluster:
    Type: String
    Description: Reference to ECS cluster
  Port80TargetGroup:
    Type: String
    Description: Reference to target group for port 80
  Port443TargetGroup:
    Type: String
    Description: Reference to target group for port 443
  PublicAlbAcmCertificate:
    #AllowedPattern: ^$|(arn:aws:acm:)([a-z0-9/:-])*([a-z0-9])$
    Description: '[ Optional ] The AWS Certification Manager certificate ARN for the ALB certificate - this certificate should be created in the region you wish to run the ALB and must reference the WordPress domain name you use below.'
    Type: String
    Default: "arn:aws:acm:us-east-1:187621470568:certificate/6504f5c8-0e04-4032-b0a2-b65deefb9b8e"
  DesiredServiceCapacity:
    Type: Number
    Default: '1'
    Description: Number of containers to launch in your ECS cluster.
  MinServiceCapacity:
    Type: Number
    Default: '1'
    Description: Minimum number of containers that can be launched in your ECS cluster.
  MaxServiceCapacity:
    Type: Number
    Default: '10'
    Description: Maximum number of containers that can be launched in your ECS cluster.
  CPUReservationNGINX:
    Type: Number
    Default: '100'
    Description: CPU reservation value for NGINX configuration 
  MemoryLimitNGINX:
    Type: Number
    Default: '300'
    Description: Hard limit to memory usage (also relevant for reservation
Conditions:
  SslCertificate:
    !Not [!Equals [ '', !Ref PublicAlbAcmCertificate ] ]
  NotSslCertificate:
    !Equals [ '', !Ref 'PublicAlbAcmCertificate' ]
Resources:
  taskdefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Join ['', [!Ref 'AWS::StackName', -bufe]]
      ContainerDefinitions:
      - Name: "bu-webrouter"
        Cpu: !Ref 'CPUReservationNGINX'
        Essential: 'true'
        # uncomment the following if we can make the root file system read-only
        #ReadonlyRootFilesystem: 'true'
        # The following is to avoid the catch-22: we don't have an image in our ECR until 
        # the CodePipeline runs and the service has already failed.  We should investigate 
        # having this be our web-router-base Docker image when we have it.
        Image: !Sub "${RouterImage}:${RouterTag}"
        #Image: amazon/amazon-ecs-sample
        #Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}"
        #Image: 
        #  "Fn::Join": 
        #    - ':' 
        #    -
        #      - "Fn::ImportValue": !Sub "${Prefix}-container-repository-uri"
        #      - "latest"
        Memory: !Ref 'MemoryLimitNGINX'
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref 'CloudwatchLogsGroup'
            awslogs-region: !Ref 'AWS::Region'
            awslogs-stream-prefix: bufe-buedu
        Environment:
          - Name: LANDSCAPE
            Value: !Ref 'Landscape'
        PortMappings:
          - ContainerPort: 80
          - ContainerPort: 443

  Port443Service:
    Condition: SslCertificate
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'ECSCluster'
      DesiredCount: !Ref 'DesiredServiceCapacity'
      LoadBalancers:
      - ContainerName: "bu-webrouter"
        ContainerPort: '443'
        TargetGroupArn: !Ref 'Port443TargetGroup'
      Role: 
        "Fn::ImportValue": !Sub "${Prefix}-container-role"
      ServiceName: !Sub "port443-${Prefix}-service"
      TaskDefinition: !Ref 'taskdefinition'

  Port443ServiceScalingTarget:
    Condition: SslCertificate
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref 'MaxServiceCapacity'
      MinCapacity: !Ref 'MinServiceCapacity'
      #ResourceId: !Ref "Port443Service" 
      ResourceId: !Join
        - /
        - - service
          - !Ref "ECSCluster"
          - !GetAtt "Port443Service.Name"
      RoleARN: 
        "Fn::ImportValue": !Sub "${Prefix}-autoscaling-role-arn" 
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  Port443TargetScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "port443-target-${AWS::StackName}-policy"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref 'Port443ServiceScalingTarget'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
          #PredefinedMetricType: ALBRequestCountPerTarget
          #ResourceLabel: 
        ScaleInCooldown: 300
        ScaleOutCooldown: 300
        TargetValue: 60

  Port80Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref 'ECSCluster'
      DesiredCount: !Ref 'DesiredServiceCapacity'
      LoadBalancers:
      - ContainerName: "bu-webrouter"
        ContainerPort: '80'
        TargetGroupArn: !Ref 'Port80TargetGroup'
      Role:
        "Fn::ImportValue": !Sub "${Prefix}-container-role"
      ServiceName: !Sub "port80-${Prefix}-service"
      TaskDefinition: !Ref 'taskdefinition'

  Port80ServiceScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref 'MaxServiceCapacity'
      MinCapacity: !Ref 'MinServiceCapacity'
      #ResourceId: !Ref "Port80Service" 
      ResourceId: !Join
        - /
        - - service
          - !Ref "ECSCluster"
          - !GetAtt "Port80Service.Name"
      RoleARN: 
        "Fn::ImportValue": !Sub "${Prefix}-autoscaling-role-arn" 
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  Port80TargetScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub "port80-target-${AWS::StackName}-policy"
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref 'Port80ServiceScalingTarget'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
          #PredefinedMetricType: ALBRequestCountPerTarget
          #ResourceLabel: 
        ScaleInCooldown: 300
        ScaleOutCooldown: 300
        TargetValue: 60

Outputs:
  Port80Service:
    Value: !Ref 'Port80Service'
    Export:
      Name: !Sub "${Prefix}-port80service-ref"
  Port443Service:
    Value: !Ref 'Port443Service'
    Export:
      Name: !Sub "${Prefix}-port443service-ref"
